import {
  // Arrows & Direction
  ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ChevronDown, ChevronLeft, 
  ChevronRight, ChevronUp, ChevronsDown, ChevronsLeft, ChevronsRight, 
  ChevronsUp, CircleArrowDown, CircleArrowLeft, CircleArrowRight, CircleArrowUp,
  CornerDownLeft, CornerDownRight, CornerLeftDown, CornerLeftUp, CornerRightDown,
  CornerRightUp, CornerUpLeft, CornerUpRight, MoveHorizontal, MoveVertical,
  
  // Business & Finance
  BadgeDollarSign, Banknote, Bank, BarChartHorizontal, BarChart, Building, 
  Calculator, Calendar, CreditCard, DollarSign, Euro, LandPlot, LineChart, 
  Landmark, Percent, PiggyBank, Receipt, ReceiptText, Scale, ShoppingCart, 
  Wallet, CircleDollarSign, Coins, Store, Building2, BuildingStore,
  
  // Communication
  AtSign, Bell, BellRing, Broadcast, Globe, Headphones, HelpCircle, Info, Mail, 
  MessageCircle, MessageSquare, Megaphone, Phone, Smartphone as SmartphoneIcon, Send, Share,
  Speech, MailOpen, MessagesSquare, BellOff, PhoneCall, PhoneForwarded, 
  PhoneIncoming, PhoneOff, PhoneOutgoing, 
  
  // Design & UI
  ActivitySquare, Activity, AlignCenter, AlignJustify, AlignLeft, AlignRight, 
  AppWindow, BringToFront, Check, Circle, CircleCheck, CircleMinus, CirclePlus, 
  CircleX, Copy, Crop, Eye, EyeOff, Figma, FilePlus, FileText, Film, Filter, 
  Fingerprint, Flag, FlipHorizontal, FlipVertical, FolderPlus, Grid, 
  ImagePlus, Image, Layers, Layout, Maximize, Minimize, Monitor, Moon, 
  MousePointer, Move, Palette, PanelLeft, PanelRight, PanelTop, Pencil, Ruler, 
  Scissors, Settings, Sliders, SmilePlus, Smile, Sparkles, Sun, 
  
  // Health & Wellness
  Apple, Baby, Bath, BedDouble, Beef, Bone, Bread, Cake, Carrot, 
  Cheese, Cherry, Cookie, Croissant, Egg, Fish, Flask, FlaskRound, 
  Heart, HeartPulse, Leaf, Pill, Pizza, Potato, Salad, Sandwich, Wheat,
  Exercise, Weight, Yoga, Meditation, Dumbbell as DumbbellFitness, Vegetable, CoinsIcon, Running,
  FirstAid, Stethoscope, Thermometer, VegetableIcon,
  
  // Technology & Devices
  Airplay, Aperture, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, 
  BatteryWarning, Battery, Bluetooth, Camera, Cast, Clipboard, Command, Compass, 
  Computer, Cpu, Database, Disc, Download, ExternalLink, File, Folder, HardDrive, 
  Hash, Headset, Link, Lock, Mic, Plug, QrCode, Radio, RotateCcw, RotateCw, Rss, 
  Save, Search, Server, Shield, Smartphone, Tablet, Tag, ToggleLeft, ToggleRight, 
  Trash, Tv, Upload, Usb, Video, Wifi, WifiOff, Zap,
  
  // Nature & Environment
  Bug, Citrus, Cloud, CloudDrizzle, CloudFog, CloudLightning, CloudRain, 
  CloudSnow, Clover, Droplets, Feather, Fish, Flame, Flower, Flower2, 
  Footprints, Leaf, Mountain, Palmtree, Plant, Recycle, Snowflake, Sun, 
  Sunrise, Sunset, ThermometerSnowflake, ThermometerSun, TreeDeciduous, 
  TreePine, Umbrella, Wind,
  
  // Transportation
  Bicycle, Bus, Car, Factory, Forklift, Fuel, MapPin, Map, Navigation, Parking, 
  Plane, RoadSign, Rocket, Route, Ship, Tractor, TrafficCone, Train, Truck, 
  
  // Sports & Activities
  Bike, Dumbbell, FlagTriangleRight, Medal, Shirt, ShoppingBag, 
  Shovel, Trophy, Target, Timer, Tent, Swim, Ski, Sailboat, Music,
  
  // Misc & Symbols
  AlertCircle, AlertTriangle, Award, Bookmark, Box, Briefcase, Bug as BugMisc, Cake as CakeMisc, 
  Coffee, Crown, Gift, Glasses, Home, Key, LightbulbOff, Lightbulb, 
  Package, Puzzle, Scan, Scissors as ScissorsMisc, ShieldAlert, ShieldCheck, Star, 
  Suitcase, SunMoon, ThumbsDown, ThumbsUp, Ticket, Tool, Umbrella as UmbrellaMisc, Users, 
  Wand, Watch, Wrench, X, ZoomIn, ZoomOut
} from 'lucide-react';

// Comprehensive icon map organized by categories
export const iconMap: Record<string, any> = {
  // Arrows & Direction
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsDown: ChevronsDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUp: ChevronsUp,
  circleArrowDown: CircleArrowDown,
  circleArrowLeft: CircleArrowLeft,
  circleArrowRight: CircleArrowRight,
  circleArrowUp: CircleArrowUp,
  cornerDownLeft: CornerDownLeft,
  cornerDownRight: CornerDownRight,
  moveHorizontal: MoveHorizontal,
  moveVertical: MoveVertical,

  // Business & Finance
  badge: BadgeDollarSign,
  banknote: Banknote,
  bank: Bank,
  barChartHorizontal: BarChartHorizontal,
  barChart: BarChart,
  building: Building,
  calculator: Calculator,
  calendar: Calendar,
  creditCard: CreditCard,
  dollar: DollarSign,
  euro: Euro,
  landPlot: LandPlot,
  lineChart: LineChart,
  landmark: Landmark,
  percent: Percent,
  piggyBank: PiggyBank,
  receipt: Receipt,
  receiptText: ReceiptText,
  scale: Scale,
  cart: ShoppingCart,
  wallet: Wallet,
  circleDollar: CircleDollarSign,
  coins: Coins,
  store: Store,
  building2: Building2,
  shop: BuildingStore,

  // Communication
  at: AtSign,
  bell: Bell,
  bellRing: BellRing,
  broadcast: Broadcast,
  globe: Globe,
  headphones: Headphones,
  help: HelpCircle,
  info: Info,
  mail: Mail,
  message: MessageCircle,
  messageSquare: MessageSquare,
  megaphone: Megaphone,
  phone: Phone,
  smartphoneComm: SmartphoneIcon,
  send: Send,
  share: Share,
  speech: Speech,
  mailOpen: MailOpen,
  messages: MessagesSquare,

  // Design & UI
  activitySquare: ActivitySquare,
  activity: Activity,
  alignCenter: AlignCenter,
  check: Check,
  circle: Circle,
  checkCircle: CircleCheck,
  minusCircle: CircleMinus,
  plusCircle: CirclePlus,
  xCircle: CircleX,
  copy: Copy,
  crop: Crop,
  eye: Eye,
  eyeOff: EyeOff,
  figma: Figma,
  filePlus: FilePlus,
  fileText: FileText,
  film: Film,
  filter: Filter,
  fingerprint: Fingerprint,
  flag: Flag,
  folderPlus: FolderPlus,
  grid: Grid,
  imagePlus: ImagePlus,
  image: Image,
  layers: Layers,
  layout: Layout,
  maximize: Maximize,
  minimize: Minimize,
  monitor: Monitor,
  moon: Moon,
  mousePointer: MousePointer,
  move: Move,
  palette: Palette,
  pencil: Pencil,
  ruler: Ruler,
  scissors: ScissorsMisc,
  settings: Settings,
  sliders: Sliders,
  smile: Smile,
  smilePlus: SmilePlus,
  sparkles: Sparkles,
  sun: Sun,

  // Health & Wellness
  apple: Apple,
  baby: Baby,
  bath: Bath,
  bed: BedDouble,
  beef: Beef,
  bone: Bone,
  bread: Bread,
  cake: CakeMisc,
  carrot: Carrot,
  cheese: Cheese,
  cherry: Cherry,
  cookie: Cookie,
  croissant: Croissant,
  egg: Egg,
  fish: Fish,
  flask: Flask,
  flaskRound: FlaskRound,
  heart: Heart,
  heartPulse: HeartPulse,
  leaf: Leaf,
  pill: Pill,
  pizza: Pizza,
  potato: Potato,
  salad: Salad,
  sandwich: Sandwich,
  wheat: Wheat,
  exercise: Exercise,
  weight: Weight,
  yoga: Yoga,
  meditation: Meditation,
  dumbbellFitness: DumbbellFitness,
  vegetables: Vegetable,
  firstAid: FirstAid,
  stethoscope: Stethoscope,
  thermometer: Thermometer,
  running: Running,

  // Technology & Devices
  airplay: Airplay,
  camera: Camera,
  cast: Cast,
  clipboard: Clipboard,
  command: Command,
  compass: Compass,
  computer: Computer,
  cpu: Cpu,
  database: Database,
  disc: Disc,
  download: Download,
  externalLink: ExternalLink,
  file: File,
  folder: Folder,
  hardDrive: HardDrive,
  hash: Hash,
  headset: Headset,
  link: Link,
  lock: Lock,
  mic: Mic,
  plug: Plug,
  qrCode: QrCode,
  radio: Radio,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  rss: Rss,
  save: Save,
  search: Search,
  server: Server,
  shield: Shield,
  smartphone: Smartphone,
  tablet: Tablet,
  tag: Tag,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trash: Trash,
  tv: Tv,
  upload: Upload,
  usb: Usb,
  video: Video,
  wifi: Wifi,
  wifiOff: WifiOff,
  zap: Zap,

  // Nature & Environment
  bug: BugMisc,
  citrus: Citrus,
  cloud: Cloud,
  rain: CloudRain,
  fog: CloudFog,
  lightning: CloudLightning,
  drizzle: CloudDrizzle,
  snow: CloudSnow,
  clover: Clover,
  droplets: Droplets,
  feather: Feather,
  flame: Flame,
  flower: Flower,
  flower2: Flower2,
  foot: Footprints,
  mountain: Mountain,
  palm: Palmtree,
  plant: Plant,
  recycle: Recycle,
  snowflake: Snowflake,
  sunrise: Sunrise,
  sunset: Sunset,
  tree: TreeDeciduous,
  pine: TreePine,
  umbrella: UmbrellaMisc,
  wind: Wind,

  // Transportation
  bicycle: Bicycle,
  bus: Bus,
  car: Car,
  factory: Factory,
  forklift: Forklift,
  fuel: Fuel,
  mapPin: MapPin,
  map: Map,
  navigation: Navigation,
  parking: Parking,
  plane: Plane,
  roadSign: RoadSign,
  rocket: Rocket,
  route: Route,
  ship: Ship,
  tractor: Tractor,
  trafficCone: TrafficCone,
  train: Train,
  truck: Truck,

  // Sports & Activities
  bike: Bike,
  dumbbell: Dumbbell,
  flagTriangle: FlagTriangleRight,
  medal: Medal,
  shirt: Shirt,
  bag: ShoppingBag,
  shovel: Shovel,
  trophy: Trophy,
  target: Target,
  timer: Timer,
  tent: Tent,
  swim: Swim,
  ski: Ski,
  sailboat: Sailboat,
  music: Music,

  // Misc & Symbols
  alert: AlertCircle,
  warning: AlertTriangle,
  award: Award,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  coffee: Coffee,
  crown: Crown,
  gift: Gift,
  glasses: Glasses,
  home: Home,
  key: Key,
  lightbulbOff: LightbulbOff,
  lightbulb: Lightbulb,
  package: Package,
  puzzle: Puzzle,
  scan: Scan,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  star: Star,
  suitcase: Suitcase,
  sunMoon: SunMoon,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  ticket: Ticket,
  tool: Tool,
  users: Users,
  wand: Wand,
  watch: Watch,
  wrench: Wrench,
  x: X,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut
};

// Icon category definitions
export const iconCategories = [
  { id: 'business', name: 'Business & Finance' },
  { id: 'health', name: 'Health & Wellness' },
  { id: 'tech', name: 'Technology & Devices' },
  { id: 'nature', name: 'Nature & Environment' },
  { id: 'transport', name: 'Transportation' },
  { id: 'sports', name: 'Sports & Activities' },
  { id: 'communication', name: 'Communication' },
  { id: 'design', name: 'Design & UI' },
  { id: 'arrows', name: 'Arrows & Direction' },
  { id: 'misc', name: 'Misc & Symbols' }
];

// Maps icon names to categories for filtering
export const iconCategoryMap: Record<string, string> = {
  // Business & Finance
  badge: 'business', banknote: 'business', bank: 'business', barChartHorizontal: 'business',
  barChart: 'business', building: 'business', calculator: 'business', calendar: 'business',
  creditCard: 'business', dollar: 'business', euro: 'business', landPlot: 'business',
  lineChart: 'business', landmark: 'business', percent: 'business', piggyBank: 'business',
  receipt: 'business', receiptText: 'business', scale: 'business', cart: 'business',
  wallet: 'business', circleDollar: 'business', coins: 'business', store: 'business',
  building2: 'business', shop: 'business',
  
  // Health & Wellness
  apple: 'health', baby: 'health', bath: 'health', bed: 'health', beef: 'health',
  bone: 'health', bread: 'health', cake: 'health', carrot: 'health', cheese: 'health',
  cherry: 'health', cookie: 'health', croissant: 'health', egg: 'health', fish: 'health',
  flask: 'health', flaskRound: 'health', heart: 'health', heartPulse: 'health',
  leaf: 'health', pill: 'health', pizza: 'health', potato: 'health', salad: 'health',
  sandwich: 'health', wheat: 'health', exercise: 'health', weight: 'health',
  yoga: 'health', meditation: 'health', dumbbellFitness: 'health', vegetables: 'health',
  firstAid: 'health', stethoscope: 'health', thermometer: 'health', running: 'health',
  
  // Technology & Devices
  airplay: 'tech', camera: 'tech', cast: 'tech', clipboard: 'tech', command: 'tech',
  compass: 'tech', computer: 'tech', cpu: 'tech', database: 'tech', disc: 'tech',
  download: 'tech', externalLink: 'tech', file: 'tech', folder: 'tech', hardDrive: 'tech',
  hash: 'tech', headset: 'tech', link: 'tech', lock: 'tech', mic: 'tech', plug: 'tech',
  qrCode: 'tech', radio: 'tech', rotateCcw: 'tech', rotateCw: 'tech', rss: 'tech',
  save: 'tech', search: 'tech', server: 'tech', shield: 'tech', smartphone: 'tech',
  tablet: 'tech', tag: 'tech', toggleLeft: 'tech', toggleRight: 'tech', trash: 'tech',
  tv: 'tech', upload: 'tech', usb: 'tech', video: 'tech', wifi: 'tech', wifiOff: 'tech', zap: 'tech',
  
  // Nature & Environment
  bug: 'nature', citrus: 'nature', cloud: 'nature', rain: 'nature', fog: 'nature',
  lightning: 'nature', drizzle: 'nature', snow: 'nature', clover: 'nature',
  droplets: 'nature', feather: 'nature', flame: 'nature', flower: 'nature',
  flower2: 'nature', foot: 'nature', mountain: 'nature', palm: 'nature', plant: 'nature',
  recycle: 'nature', snowflake: 'nature', sunrise: 'nature', sunset: 'nature',
  tree: 'nature', pine: 'nature', umbrella: 'nature', wind: 'nature',
  
  // Transportation
  bicycle: 'transport', bus: 'transport', car: 'transport', factory: 'transport',
  forklift: 'transport', fuel: 'transport', mapPin: 'transport', map: 'transport',
  navigation: 'transport', parking: 'transport', plane: 'transport', roadSign: 'transport',
  rocket: 'transport', route: 'transport', ship: 'transport', tractor: 'transport',
  trafficCone: 'transport', train: 'transport', truck: 'transport',
  
  // Sports & Activities
  bike: 'sports', dumbbell: 'sports', flagTriangle: 'sports', medal: 'sports',
  shirt: 'sports', bag: 'sports', shovel: 'sports', trophy: 'sports', target: 'sports',
  timer: 'sports', tent: 'sports', swim: 'sports', ski: 'sports', sailboat: 'sports',
  music: 'sports',
  
  // Communication
  at: 'communication', bell: 'communication', bellRing: 'communication', broadcast: 'communication',
  globe: 'communication', headphones: 'communication', help: 'communication', info: 'communication',
  mail: 'communication', message: 'communication', messageSquare: 'communication',
  megaphone: 'communication', phone: 'communication', smartphoneComm: 'communication',
  send: 'communication', share: 'communication', speech: 'communication',
  mailOpen: 'communication', messages: 'communication',
  
  // Design & UI
  activitySquare: 'design', activity: 'design', alignCenter: 'design', check: 'design',
  circle: 'design', checkCircle: 'design', minusCircle: 'design', plusCircle: 'design',
  xCircle: 'design', copy: 'design', crop: 'design', eye: 'design', eyeOff: 'design',
  figma: 'design', filePlus: 'design', fileText: 'design', film: 'design', filter: 'design',
  fingerprint: 'design', flag: 'design', folderPlus: 'design', grid: 'design',
  imagePlus: 'design', image: 'design', layers: 'design', layout: 'design', maximize: 'design',
  minimize: 'design', monitor: 'design', moon: 'design', mousePointer: 'design',
  move: 'design', palette: 'design', pencil: 'design', ruler: 'design', scissors: 'design',
  settings: 'design', sliders: 'design', smile: 'design', smilePlus: 'design',
  sparkles: 'design', sun: 'design',
  
  // Arrows & Direction
  arrowDown: 'arrows', arrowLeft: 'arrows', arrowRight: 'arrows', arrowUp: 'arrows',
  chevronDown: 'arrows', chevronLeft: 'arrows', chevronRight: 'arrows', chevronUp: 'arrows',
  chevronsDown: 'arrows', chevronsLeft: 'arrows', chevronsRight: 'arrows', chevronsUp: 'arrows',
  circleArrowDown: 'arrows', circleArrowLeft: 'arrows', circleArrowRight: 'arrows',
  circleArrowUp: 'arrows', cornerDownLeft: 'arrows', cornerDownRight: 'arrows',
  moveHorizontal: 'arrows', moveVertical: 'arrows',
  
  // Misc & Symbols
  alert: 'misc', warning: 'misc', award: 'misc', bookmark: 'misc', box: 'misc',
  briefcase: 'misc', coffee: 'misc', crown: 'misc', gift: 'misc', glasses: 'misc',
  home: 'misc', key: 'misc', lightbulbOff: 'misc', lightbulb: 'misc', package: 'misc',
  puzzle: 'misc', scan: 'misc', shieldAlert: 'misc', shieldCheck: 'misc', star: 'misc',
  suitcase: 'misc', sunMoon: 'misc', thumbsDown: 'misc', thumbsUp: 'misc', ticket: 'misc',
  tool: 'misc', users: 'misc', wand: 'misc', watch: 'misc', wrench: 'misc', x: 'misc',
  zoomIn: 'misc', zoomOut: 'misc'
}; 